version: '3.8'

services:
  nextapi:
    image: postgres:15.3
    container_name: nextapi
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data